apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
     app: myjavaapp
spec:
  replicas: 3
  selector:
    matchLabels:
         app: myjavaapp
  template:
     metadata:
       labels:
         app: javaapp
     spec:
       containers:
       - name: myjavaapp-container
         image: rohitsharma93/myjavaapp5may22
         ports:
         - containerPort: 8080