apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp-deploy
  labels: 
     app: javaapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp-container
        image: rohitsharma93/myjenkins3may 
        ports:
        - containerPort: 8080
