apiVersion: v1
kind: ReplicationController
metadata:
  name: javaapp-kc
spec:
  replicas: 5
  
  selector:
    app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javaapp-container
          image: rohitsharma93/myjenkins3may
          ports:
            - containerPort: 8080
