apiVersion: v1
kind: ReplicationController
metadata:
   name: javaapp-rc
spec:
  replicas: 5
  selector:
     app: javaapp
     version: 2.6.1
  template:
    metadata:
      labels:
          app: javaapp
          version: 2.6.1
    spec:
      containers:
       - name: javaapp-container
         image: rohitsharma93/myjenkins2may
         ports:
         - containerPort: 8080
