apiVersion: v1
kind: ReplicationController
metadata:
   name: nginx-rc
spec:
  replicas: 3
  selector:
     app: nginx
  template:
    metadata:
      labels:
          app: nginx
    spec:
      containers:
       - name: nginx-container
         image: rohitsharma93/myjenkins2may
         ports:
         - containerPort: 80
