apiVersion: v1
kind: ReplicationController
metadata:
   name: javaapp-rc
spec:
  replicas: 5
  selector:
     app: javaapp
  template:
    metadata:
      labels:
          app: javaapp
    spec:
      containers:
       - name: javaapp-container
         image: rohitsharma93/myjenkins2may
         ports:
         - containerPort: 8080
