apiVersion: v1
kind: ReplicationController
metadata:
   name: javaapp-rs
spec:
  replicas: 3
  selector:
     app: javaapp
  template:
    metadata: 
      labels:
          app: javaapp
    spec:
      containers:
       - name: javaapp-container
         image: rohitsharma93/myjenkins2may:1
         ports:
         - containerPort: 8080
