apiVersion: v1 
kind: ReplicationController
metadata:
  name: mynginx-rs
spec:
  replicas: 3
  selector:
    app: mynginx
  template:
    metadata:
     labels:
        app: mynginx
    spec:
      containers:
        - name: mynginx-container
          image: mynginx
          ports:
            - containerPort: 80
