apiVersion: v1
kind: Service
metadata:
  name: myjenkinsapp-svc
  labels: 
   app: myjenkinsapp
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myjenkinsapp
    
  
